-- Seed Daily Questions (Quizzes)
-- Categories: fun, deep, spicy, romantic

DELETE FROM public.user_answers WHERE activity_id IN (SELECT id FROM public.activities WHERE type = 'quiz');
DELETE FROM public.activities WHERE type = 'quiz';

INSERT INTO public.activities (category, type, content) VALUES
-- FUN & HYPOTHETICAL
('fun', 'quiz', '{"question": "If you could be any fictional character for a day, who would you choose?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the most ridiculous outfit you''ve ever worn?", "options": []}'),
('fun', 'quiz', '{"question": "If animals could talk, which one would be the rudest?", "options": []}'),
('fun', 'quiz', '{"question": "What would your wrestling name be?", "options": []}'),
('fun', 'quiz', '{"question": "If you had to eat one food for the rest of your life, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the weirdest smell you actually enjoy?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a kitchen appliance, which one would you be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the worst pickup line you''ve ever heard?", "options": []}'),
('fun', 'quiz', '{"question": "If you could shrink any animal to the size of a puppy, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the most useless superpower you can imagine?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a ghost, how would you haunt people?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the funniest way you''ve injured yourself?", "options": []}'),
('fun', 'quiz', '{"question": "If you could ban one word from the dictionary, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What would the title of your autobiography be?", "options": []}'),
('fun', 'quiz', '{"question": "If you could trade lives with a celebrity for a week, who would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the strangest thing you''ve ever eaten?", "options": []}'),
('fun', 'quiz', '{"question": "If you could instantly become an expert in something, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s your favorite dad joke?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a vegetable, which one would you be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the most embarrassing thing you''ve done in public?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have a conversation with any inanimate object, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the weirdest dream you''ve ever had?", "options": []}'),
('fun', 'quiz', '{"question": "If you could create a new holiday, what would it celebrate?", "options": []}'),
('fun', 'quiz', '{"question": "What''s your spirit animal and why?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a color, which one would you be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the most random fact you know?", "options": []}'),
('fun', 'quiz', '{"question": "If you could live in any movie universe, which one would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s your favorite meme?", "options": []}'),
('fun', 'quiz', '{"question": "If you could only listen to one song for the rest of your life, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the worst gift you''ve ever received?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a flavor of ice cream, what would you be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the most adventurous thing you''ve ever done?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have dinner with any historical figure, who would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s your favorite board game?", "options": []}'),
('fun', 'quiz', '{"question": "If you could teleport anywhere right now, where would you go?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the best prank you''ve ever pulled?", "options": []}'),
('fun', 'quiz', '{"question": "If you could be a contestant on any game show, which one would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s your guilty pleasure TV show?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have any exotic animal as a pet, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the most unusual talent you have?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a type of candy, what would you be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s your favorite childhood cartoon?", "options": []}'),
('fun', 'quiz', '{"question": "If you could swap bodies with me for a day, what would you do?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the funniest thing that''s happened to us?", "options": []}'),
('fun', 'quiz', '{"question": "If we were a dynamic duo, who would we be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the most spontaneous thing we''ve ever done?", "options": []}'),
('fun', 'quiz', '{"question": "If we started a band, what would we call it?", "options": []}'),
('fun', 'quiz', '{"question": "What''s your favorite photo of us?", "options": []}'),
('fun', 'quiz', '{"question": "If we could star in a movie together, what genre would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What''s the silliest argument we''ve ever had?", "options": []}'),
('fun', 'quiz', '{"question": "Zombie apocalypse: What is your weapon of choice?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have an unlimited supply of one thing, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the weirdest thing you have ever bought?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a wrestler, what would be your entrance theme song?", "options": []}'),
('fun', 'quiz', '{"question": "What is the most useless talent you possess?", "options": []}'),
('fun', 'quiz', '{"question": "If you could be any age for a week, what age would you be?", "options": []}'),
('fun', 'quiz', '{"question": "If you had to wear a costume every day for a year, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest movie you have ever seen?", "options": []}'),
('fun', 'quiz', '{"question": "If you could rename yourself, what name would you pick?", "options": []}'),
('fun', 'quiz', '{"question": "What is the weirdest food combination you enjoy?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a superhero, what would be your weakness?", "options": []}'),
('fun', 'quiz', '{"question": "What is the most embarrassing song on your playlist?", "options": []}'),
('fun', 'quiz', '{"question": "If you could only eat three foods for the rest of your life, what would they be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the strangest habit you have?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a mythical creature, which one would you be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest thing you believed as a child?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have any job in the world for one day, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the most ridiculous thing you have ever cried over?", "options": []}'),
('fun', 'quiz', '{"question": "If you could be invisible for a day, what would you do?", "options": []}'),
('fun', 'quiz', '{"question": "What is the weirdest thing in your fridge right now?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have a personal mascot, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest nickname you have ever had?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a villain, what would be your evil plan?", "options": []}'),
('fun', 'quiz', '{"question": "What is the most awkward date you have ever been on (before us)?", "options": []}'),
('fun', 'quiz', '{"question": "If you could only use one emoji for the rest of your life, which one would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the weirdest gift you have ever given someone?", "options": []}'),
('fun', 'quiz', '{"question": "If you could be a character in a video game, who would you be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest thing you have ever seen a stranger do?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have a robot do one chore for you, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the most random thing you have memorized?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a cereal, what would you be called?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest word in the English language?", "options": []}'),
('fun', 'quiz', '{"question": "If you could live in a TV show, which one would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the weirdest thing you have ever Googled?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have a conversation with your pet, what would you say?", "options": []}'),
('fun', 'quiz', '{"question": "What is the most ridiculous fashion trend you followed?", "options": []}'),
('fun', 'quiz', '{"question": "If you were a potato, how would you like to be cooked?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest thing that has happened to you at work?", "options": []}'),
('fun', 'quiz', '{"question": "If you could be a fly on the wall, where would you go?", "options": []}'),
('fun', 'quiz', '{"question": "What is the weirdest thing you have ever found on the ground?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have a theme park based on your life, what would the main attraction be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest thing you have ever said in your sleep?", "options": []}'),
('fun', 'quiz', '{"question": "If you could be a professional athlete in any sport, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the most bizarre dream you have ever had?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have a lifetime supply of any candy, what would it be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest thing you have ever overheard?", "options": []}'),
('fun', 'quiz', '{"question": "If you could be a character in a horror movie, who would you be?", "options": []}'),
('fun', 'quiz', '{"question": "What is the weirdest thing you have ever eaten for breakfast?", "options": []}'),
('fun', 'quiz', '{"question": "If you could have a clone, what would you make them do?", "options": []}'),
('fun', 'quiz', '{"question": "What is the funniest thing you have ever seen on social media?", "options": []}'),

-- DEEP CONNECTION & 36 QUESTIONS
('deep', 'quiz', '{"question": "Given the choice of anyone in the world, whom would you want as a dinner guest?", "options": []}'),
('deep', 'quiz', '{"question": "Would you like to be famous? In what way?", "options": []}'),
('deep', 'quiz', '{"question": "Before making a telephone call, do you ever rehearse what you are going to say? Why?", "options": []}'),
('deep', 'quiz', '{"question": "What would constitute a ''perfect'' day for you?", "options": []}'),
('deep', 'quiz', '{"question": "When did you last sing to yourself? To someone else?", "options": []}'),
('deep', 'quiz', '{"question": "If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?", "options": []}'),
('deep', 'quiz', '{"question": "Do you have a secret hunch about how you will die?", "options": []}'),
('deep', 'quiz', '{"question": "Name three things you and I appear to have in common.", "options": []}'),
('deep', 'quiz', '{"question": "For what in your life do you feel most grateful?", "options": []}'),
('deep', 'quiz', '{"question": "If you could change anything about the way you were raised, what would it be?", "options": []}'),
('deep', 'quiz', '{"question": "Take four minutes and tell me your life story in as much detail as possible.", "options": []}'),
('deep', 'quiz', '{"question": "If you could wake up tomorrow having gained any one quality or ability, what would it be?", "options": []}'),
('deep', 'quiz', '{"question": "If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?", "options": []}'),
('deep', 'quiz', '{"question": "Is there something that you''ve dreamed of doing for a long time? Why haven''t you done it?", "options": []}'),
('deep', 'quiz', '{"question": "What is the greatest accomplishment of your life?", "options": []}'),
('deep', 'quiz', '{"question": "What do you value most in a friendship?", "options": []}'),
('deep', 'quiz', '{"question": "What is your most treasured memory?", "options": []}'),
('deep', 'quiz', '{"question": "What is your most terrible memory?", "options": []}'),
('deep', 'quiz', '{"question": "If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?", "options": []}'),
('deep', 'quiz', '{"question": "What does friendship mean to you?", "options": []}'),
('deep', 'quiz', '{"question": "What roles do love and affection play in your life?", "options": []}'),
('deep', 'quiz', '{"question": "Alternate sharing something you consider a positive characteristic of your partner. Share a total of five items.", "options": []}'),
('deep', 'quiz', '{"question": "How close and warm is your family? Do you feel your childhood was happier than most other people''s?", "options": []}'),
('deep', 'quiz', '{"question": "How do you feel about your relationship with your mother?", "options": []}'),
('deep', 'quiz', '{"question": "Make three true ''we'' statements each. For instance, ''We are both in this room feeling...''", "options": []}'),
('deep', 'quiz', '{"question": "Complete this sentence: ''I wish I had someone with whom I could share...''", "options": []}'),
('deep', 'quiz', '{"question": "If you were going to become a close friend with your partner, please share what would be important for him or her to know.", "options": []}'),
('deep', 'quiz', '{"question": "Tell your partner what you like about them; be very honest this time, saying things that you might not say to someone you''ve just met.", "options": []}'),
('deep', 'quiz', '{"question": "Share with your partner an embarrassing moment in your life.", "options": []}'),
('deep', 'quiz', '{"question": "When did you last cry in front of another person? By yourself?", "options": []}'),
('deep', 'quiz', '{"question": "Tell your partner something that you like about them already.", "options": []}'),
('deep', 'quiz', '{"question": "What, if anything, is too serious to be joked about?", "options": []}'),
('deep', 'quiz', '{"question": "If you were to die this evening with no opportunity to communicate with anyone, what would you most regret not having told someone? Why haven''t you told them yet?", "options": []}'),
('deep', 'quiz', '{"question": "Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?", "options": []}'),
('deep', 'quiz', '{"question": "Of all the people in your family, whose death would you find most disturbing? Why?", "options": []}'),
('deep', 'quiz', '{"question": "Share a personal problem and ask your partner''s advice on how he or she might handle it.", "options": []}'),
('deep', 'quiz', '{"question": "What does ''unconditional love'' mean to you?", "options": []}'),
('deep', 'quiz', '{"question": "When do you feel most vulnerable?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you wish I understood better about you?", "options": []}'),
('deep', 'quiz', '{"question": "What is your biggest fear about our future?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing I do that makes you feel safe?", "options": []}'),
('deep', 'quiz', '{"question": "What is a dream you''ve let go of?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most important lesson you''ve learned from a past relationship?", "options": []}'),
('deep', 'quiz', '{"question": "How do you define ''intimacy''?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to achieve together in the next 5 years?", "options": []}'),
('deep', 'quiz', '{"question": "What is a memory of us that you cherish the most?", "options": []}'),
('deep', 'quiz', '{"question": "How has your definition of love changed over time?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you appreciate about my personality?", "options": []}'),
('deep', 'quiz', '{"question": "What is a challenge we''ve faced that made us stronger?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to be remembered for?", "options": []}'),
('deep', 'quiz', '{"question": "Describe a moment you felt proud of me.", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you would change about yourself?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most meaningful gift you have ever received?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to do before you die?", "options": []}'),
('deep', 'quiz', '{"question": "What is your idea of a perfect relationship?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you are afraid to tell me?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most important thing in your life right now?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you wish we did more of?", "options": []}'),
('deep', 'quiz', '{"question": "What is your biggest regret?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing that always makes you smile?", "options": []}'),
('deep', 'quiz', '{"question": "What is the best advice you have ever received?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to improve in our relationship?", "options": []}'),
('deep', 'quiz', '{"question": "What is your favorite thing about yourself?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you are looking forward to?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most romantic thing I have ever done for you?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to learn?", "options": []}'),
('deep', 'quiz', '{"question": "What is your biggest insecurity?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you would do if you had no fear?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most important value you want to pass on to our children (if any)?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you appreciate about our life together?", "options": []}'),
('deep', 'quiz', '{"question": "What is your favorite way to spend a weekend?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to change about the world?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most beautiful place you have ever been?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing that makes you feel loved?", "options": []}'),
('deep', 'quiz', '{"question": "What is your favorite family tradition?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you are passionate about?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most difficult decision you have ever made?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to achieve in your career?", "options": []}'),
('deep', 'quiz', '{"question": "What is your favorite way to relax?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you are grateful for today?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most inspiring book you have ever read?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to do together this year?", "options": []}'),
('deep', 'quiz', '{"question": "What is your favorite thing about me?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you wish you could tell your younger self?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most important lesson you have learned this year?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing that makes our relationship unique?", "options": []}'),
('deep', 'quiz', '{"question": "What is your favorite memory from our first year together?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing you want to be better at?", "options": []}'),
('deep', 'quiz', '{"question": "What is the most courageous thing you have ever done?", "options": []}'),
('deep', 'quiz', '{"question": "What is one thing that brings you joy?", "options": []}'),

-- SPICY & CHEEKY (17+)
('spicy', 'quiz', '{"question": "What''s a fantasy you''ve never shared with anyone?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the hottest dream you''ve ever had about me?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s your favorite part of my body?", "options": []}'),
('spicy', 'quiz', '{"question": "If we were alone in an elevator, what would you want to do?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a song that gets you in the mood?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the most adventurous place you''d like to be intimate?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something I do that turns you on instantly?", "options": []}'),
('spicy', 'quiz', '{"question": "Do you prefer lights on or off?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s your favorite time of day for intimacy?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a roleplay scenario you''ve always wanted to try?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the best kiss we''ve ever had?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a piece of clothing you love seeing me wear?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s your favorite position?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something new you''d like to try in the bedroom?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the most sensitive part of your body?", "options": []}'),
('spicy', 'quiz', '{"question": "How important is foreplay to you?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a dirty secret you''ve kept?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the wildest thing you''ve ever done?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a word that turns you on?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something you''d like me to do to you right now?", "options": []}'),
('spicy', 'quiz', '{"question": "Do you like it when I take control?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a memory of us that makes you blush?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s your favorite way to be touched?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something that instantly kills the mood for you?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the most romantic thing I''ve ever done for you?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a scent that arouses you?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s your opinion on PDA?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something you''re curious about exploring?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the sexiest thing I''ve ever said to you?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a toy you''d be interested in trying?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s your favorite lingerie on me?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a movie scene that turns you on?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the longest you''ve gone without sex?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a compliment that makes you feel sexy?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something you want to do on our next date night?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a boundary you have in the bedroom?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something that makes you feel confident?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a guilty pleasure you have?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the most spontaneous thing we''ve done in bed?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something you want more of in our relationship?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a text message I could send that would turn you on?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s your favorite way to initiate intimacy?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a sound that turns you on?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something you''ve always wanted to ask me but were too shy?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s the most intense orgasm you''ve ever had?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something you find incredibly sexy about me?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a place you''ve always wanted to have sex?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s your favorite thing about our sex life?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s something you''d like to change about our sex life?", "options": []}'),
('spicy', 'quiz', '{"question": "What''s a fantasy involving food?", "options": []}'),
('spicy', 'quiz', '{"question": "What is the dirtiest dream you have ever had?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever skinny dipped?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite place to be kissed?", "options": []}'),
('spicy', 'quiz', '{"question": "What is the most unusual place you have had sex?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your biggest turn-on?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your biggest turn-off?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever sent a naughty photo?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite sex position?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had a one-night stand?", "options": []}'),
('spicy', 'quiz', '{"question": "What is the most daring thing you have done in bed?", "options": []}'),
('spicy', 'quiz', '{"question": "Do you like dirty talk?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite type of underwear?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever been caught having sex?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite sex toy?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a public place?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite part of foreplay?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever role-played in bed?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to wear to bed?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a car?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do after sex?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had a sex dream about someone else?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do to me?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever watched porn together?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing about my body?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex on a beach?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do in the shower?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a pool?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do in the morning?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a tent?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do at night?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex on a plane?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do on a date?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a movie theater?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do on vacation?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a bathroom?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do on a rainy day?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a dressing room?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do on a sunny day?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a park?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do in the snow?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a forest?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do in the fall?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a field?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do in the spring?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a barn?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do in the summer?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a boat?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do in the winter?", "options": []}'),
('spicy', 'quiz', '{"question": "Have you ever had sex in a hot tub?", "options": []}'),
('spicy', 'quiz', '{"question": "What is your favorite thing to do on a holiday?", "options": []}'),

-- ROMANTIC & CONNECTION
('romantic', 'quiz', '{"question": "What is your favorite love song?", "options": []}'),
('romantic', 'quiz', '{"question": "What is the most romantic movie you have ever seen?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your idea of a perfect date?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite flower?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite chocolate?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite scent on me?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to do together?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite memory of us?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing about our relationship?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite nickname for me?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to do for me?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing I do for you?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite way to show love?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite way to receive love?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to talk about?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to dream about?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to plan together?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to celebrate?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to laugh about?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to cry about?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to worry about?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to hope for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to wish for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to pray for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be thankful for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be proud of?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be excited about?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be surprised by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be inspired by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be challenged by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be comforted by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be supported by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be understood by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be accepted by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be forgiven by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be loved by?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to love?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to live for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to die for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to fight for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to work for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to wait for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to look for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to listen for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to watch for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to feel for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to think for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to speak for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to act for?", "options": []}'),
('romantic', 'quiz', '{"question": "What is your favorite thing to be?", "options": []}');

