-- Seed Daily Challenges
-- Frequency: daily
-- Mix: ~20% Competitive

DELETE FROM activities WHERE type = 'challenge' AND content->>'frequency' = 'daily';

INSERT INTO public.activities (category, type, content) VALUES
-- COMPETITIVE (approx 60)
('active', 'challenge', '{"frequency": "daily", "title": "Steps Battle", "description": "Who walked more today? Share your step count.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Best Photo", "description": "Take a photo of something that makes you happy. Best photo wins!", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Quick Trivia", "description": "First to answer a trivia question correctly wins.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Plank Off", "description": "Who can hold a plank longer right now?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Hydration Check", "description": "Send a video of you drinking water dramatically.", "durationMinutes": 2, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Push-up Challenge", "description": "Who can do more push-ups in 1 minute?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Staring Contest", "description": "Video call staring contest. First to blink loses!", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Doodle Battle", "description": "Draw a cat in 30 seconds. Best doodle wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Emoji Decode", "description": "Send a phrase in emojis. First to guess it wins.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Wall Sit", "description": "Who can hold a wall sit longer?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Rock Paper Scissors", "description": "Play Rock Paper Scissors on video call. Best of 3.", "durationMinutes": 2, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Haiku Off", "description": "Write a haiku about lunch. Best one wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Funny Face", "description": "Send your funniest face. Partner rates 1-10.", "durationMinutes": 2, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Jumping Jacks", "description": "Who can do 50 jumping jacks faster?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Prediction", "description": "Guess what your partner is wearing right now.", "durationMinutes": 2, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Caption This", "description": "Send a weird photo. Best caption wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Song Guess", "description": "Hum a song. First to guess wins.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Squat Challenge", "description": "Who can do more squats in 1 minute?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Alphabet Game", "description": "Name animals A-Z. First to fail loses.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Bad Portrait", "description": "Draw each other with non-dominant hand. Best one wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Rhyme Time", "description": "Pick a word. Take turns rhyming. First to fail loses.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Balance Test", "description": "Who can stand on one leg longer (eyes closed)?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Two Truths One Lie", "description": "Guess the lie. Winner gets a wish.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Limerick", "description": "Write a limerick about your partner. Funniest wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Memory Test", "description": "List 10 items. Partner recalls them. Most correct wins.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Lunge Off", "description": "Who can do more lunges in 1 minute?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Joke Off", "description": "Tell jokes. First to laugh loses.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Origami", "description": "Make a paper plane. Whose flies furthest?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Lip Read", "description": "Mouth a phrase on video. Partner guesses.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Burpee Challenge", "description": "Who can do 10 burpees faster?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "High Card", "description": "Draw a card (or use app). High card wins.", "durationMinutes": 2, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Story Continue", "description": "One word at a time story. First to stall loses.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Virtual Thumb War", "description": "Play a thumb war game on your phones together.", "durationMinutes": 2, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Toe Touch", "description": "Who can touch their toes with straighter legs?", "durationMinutes": 2, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Guess the Number", "description": "Guess a number 1-100. Closest wins.", "durationMinutes": 2, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Rap Battle", "description": "4 bars each. Best rhymes win.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Charades", "description": "Act out a movie. Partner guesses. Time it.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Sit-up Challenge", "description": "Who can do more sit-ups in 1 minute?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Random Number", "description": "Pick a number 1-6. If you match, you win a virtual kiss.", "durationMinutes": 2, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Photo Scavenger", "description": "Find something that reminds you of us. First to send photo wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Never Have I Ever", "description": "Play 5 rounds. Most fingers left wins.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Breath Hold", "description": "Who can hold their breath longer? (Be safe!)", "durationMinutes": 2, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "20 Questions", "description": "Guess the object in fewer questions.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Tower Build", "description": "Build a tower of cards/objects. Highest wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Tongue Twister", "description": "Say a tongue twister 3x fast. No mistakes wins.", "durationMinutes": 2, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Handstand", "description": "Who can hold a handstand (against wall) longer?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Silent Laugh", "description": "Try to make partner laugh without sound.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Blind Drawing", "description": "Draw something with eyes closed. Best one wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Word Association", "description": "Fast paced. First to hesitate loses.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Calf Raises", "description": "Who can do more calf raises before burning out?", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Guess the Price", "description": "Show an item. Guess the price. Closest wins.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Shadow Puppet", "description": "Make a shadow puppet. Best one wins.", "durationMinutes": 2, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Trivia: Movies", "description": "Ask 3 movie questions. Most correct wins.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Flexibility", "description": "Who can do the splits (or get closer)?", "durationMinutes": 2, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Trivia: History", "description": "Ask 3 history questions. Most correct wins.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Food Art", "description": "Make a face with your food. Best one wins.", "durationMinutes": 5, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Trivia: Science", "description": "Ask 3 science questions. Most correct wins.", "durationMinutes": 5, "isCompetition": true}'),
('active', 'challenge', '{"frequency": "daily", "title": "Statue Challenge", "description": "Freeze on video call. First to move loses.", "durationMinutes": 2, "isCompetition": true}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Trivia: Music", "description": "Ask 3 music questions. Most correct wins.", "durationMinutes": 5, "isCompetition": true}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Paper Toss", "description": "Toss paper ball into bin from distance. First to make it.", "durationMinutes": 5, "isCompetition": true}'),

-- NORMAL (approx 240)
('fun', 'challenge', '{"frequency": "daily", "title": "Morning Selfie", "description": "Send a selfie to your partner as soon as you wake up.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Gratitude Note", "description": "Write a physical note of gratitude and send a photo of it.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Song Dedication", "description": "Send a song that reminds you of your partner.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Virtual Hug", "description": "Send a GIF or video of yourself giving a hug.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Video Compliment", "description": "Send a video giving your partner a genuine compliment.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Act a Joke", "description": "Record yourself telling a joke.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Outfit Check", "description": "Share a photo of your outfit today.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Lunch Snap", "description": "Send a photo of your lunch and rate it 1-10.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Voice Note Love", "description": "Send a 30-second voice note saying why you love them.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Emoji Story", "description": "Tell a short story using only emojis.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Throwback Photo", "description": "Send an old photo of the two of you.", "durationMinutes": 10, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Dream Destination", "description": "Send a photo of a place you want to visit together.", "durationMinutes": 10, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Coffee/Tea Toast", "description": "Send a photo/video toasting with your drink.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Stretch Together", "description": "Do a 5-minute stretch and share a pic.", "durationMinutes": 10, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Doodle", "description": "Draw a quick doodle and send it.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Sky Photo", "description": "Send a photo of the sky and tell me what you see in the clouds.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Hydration Check", "description": "Send a video of you drinking water.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Trivia Host", "description": "Record yourself asking a trivia question like a game show host.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Mood Selfie", "description": "Send a selfie that represents your current mood.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Vision Board", "description": "Find an image representing a future goal and share it.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Funny Face Selfie", "description": "Send a selfie making a funny face.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Style Swap", "description": "Find a photo of a celebrity style you think I''d look good in.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Mood Song", "description": "Share a song that fits your mood today.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Current View", "description": "Send a photo of your view right now.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Gratitude Video", "description": "Send a video saying one thing you''re grateful for.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Big Hug", "description": "Open your arms wide in a photo like you''re hugging me.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "First Meeting", "description": "Find a photo from the year we met.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Foreign Love", "description": "Record yourself saying ''I love you'' in a different language.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Good Day Voice", "description": "Send a voice note wishing them a good day with high energy.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Smile Photo", "description": "Share a photo of something that made you smile.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Day Rating", "description": "Rate your day 1-10 with a selfie showing the number on your fingers.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Laughter Challenge", "description": "Send a video trying not to laugh.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Goal Share", "description": "Share a photo related to a goal you have.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Foodie Snap", "description": "Take an artistic photo of your food.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Water Toast", "description": "Cheers to us with a glass of water (video/photo).", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Heart Hunt", "description": "Find a heart shape in real life and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Fact Video", "description": "Record yourself sharing a random fact.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "This or That", "description": "Send a photo of two things and ask me to choose.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Shoe Selfie", "description": "Send a photo of our shoes (or just yours) imagining we are walking together.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Admiration Video", "description": "Send a video telling me something you admire.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Weekend Vibe", "description": "Send a GIF that represents your weekend plans.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Cute Animal", "description": "Find a cute animal photo/video and send it.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Riddle Video", "description": "Read a riddle on video. Can I solve it?", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Quote Art", "description": "Write an inspiring quote on paper and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Drink Selfie", "description": "Take a selfie with your favorite drink.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Excitement Face", "description": "Show me your ''excited face'' in a selfie.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Air Kiss", "description": "Send a video blowing an air kiss.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Struggle Share", "description": "Share a photo of something you''re working on.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Special Reason", "description": "Voice note: ''You are special because...''", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Sky Wish", "description": "Whisper a wish to the sky in a video.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Song Lip Sync", "description": "Lip sync to a romantic song.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Meme Reaction", "description": "Recreate a funny meme face.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Bed Selfie", "description": "Send a selfie from bed (morning or night).", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Spicy Text", "description": "Send a flirty text message.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Dream Drawing", "description": "Draw a scene from your dream (badly is fine!).", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Podcast Clip", "description": "Record a snippet of a podcast you like.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "3 Words", "description": "Write 3 words that describe your day on your hand.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Desk Tour", "description": "Give a 10-second video tour of your workspace.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "High Five Video", "description": "Slap the camera (gently) for a virtual high five.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Book Passage", "description": "Take a photo of a page you are reading.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Snack Review", "description": "Review your snack like a food critic on video.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Plant Selfie", "description": "Take a selfie with a plant.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Miss You Video", "description": "Send a video saying ''I miss you'' in a funny voice.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Laugh Audio", "description": "Record your laugh. Just your laugh.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Superpower Pose", "description": "Strike a pose demonstrating your imaginary superpower.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Cool Find", "description": "Send a photo of the coolest thing you saw today.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Motivation Voice", "description": "Record a motivational speech for me.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Recipe Hunt", "description": "Find a recipe we should cook and send the link.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Movie Trailer", "description": "Describe a movie plot badly in a voice note.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Cloud Animal", "description": "Draw on a cloud photo to show what animal it looks like.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Learn & Share", "description": "Teach me one new thing in a 30-second video.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Wish Jar", "description": "Write a wish on paper and put it in a jar/box.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Happy Dance", "description": "Do a happy dance and send a video.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Car Karaoke", "description": "Record yourself singing in the car (or anywhere).", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Secret Whisper", "description": "Whisper a secret in a voice note.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Hobby Demo", "description": "Show me something you made/did recently.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Color Hunt", "description": "Find 3 things of my favorite color and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Explore Wish", "description": "Send a map screenshot of a place you want to go.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Proud Face", "description": "Make a face that says ''I''m proud of you''.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Travel Bag", "description": "Pack a bag for a fake trip and show me what''s inside.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Animal Match", "description": "Find an animal that reminds you of me.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Nature Sound", "description": "Record a cool sound from nature.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Funny Story", "description": "Tell a funny story in a voice note.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Movie Night", "description": "Set up a cozy movie spot and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Food Craving", "description": "Draw the food you are craving right now.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Sign Selfie", "description": "Take a selfie with a street sign.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Beautiful Thing", "description": "Take a photo of the most beautiful thing you see.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "TV Commentary", "description": "Record 10 seconds of commentary on what you''re watching.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Season Snap", "description": "Take a photo that represents the current season.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Shadow Kiss", "description": "Try to kiss my shadow (or a photo of me).", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Future Prediction", "description": "Predict something about the future in a video.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Game Face", "description": "Show me your competitive game face.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Drink Cheers", "description": "Cheers to the camera with your beverage.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Reflection", "description": "Take a photo of your reflection in a window.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Appreciation Note", "description": "Write ''I appreciate you'' on a post-it and stick it somewhere.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "News Reader", "description": "Read a headline in a romantic voice.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Sporty Pose", "description": "Strike a pose like a pro athlete.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Soft Texture", "description": "Find something soft and describe how it feels.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Challenge Accepted", "description": "Send a video saying ''Challenge Accepted'' dramatically.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Love Quote", "description": "Find a cheesy love quote and read it seriously.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Holiday Spirit", "description": "Wear something festive (or silly) and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Bright Color", "description": "Find something bright yellow and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Thinking Face", "description": "Send a selfie making a deep thinking face.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Funny Video Share", "description": "Find a funny video online and share the link.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Dessert Wish", "description": "Send a photo of a dessert you wish we were sharing.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Pattern Find", "description": "Find a striped pattern and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Joke Delivery", "description": "Deliver a joke with a straight face.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Song Lyric Write", "description": "Write down a song lyric and send a photo.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Scent Guess", "description": "Describe a smell. Can I guess what it is?", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Heart Hands", "description": "Make a heart with your hands and take a pic.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "You Are Amazing", "description": "Yell ''You are amazing'' (or whisper it) in a video.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Childhood Toy", "description": "Find a photo of a childhood toy (or draw it).", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Sound Guess", "description": "Make a sound with an object. Can I guess it?", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Color Match", "description": "Wear something that matches my eyes.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Riddle Solver", "description": "Send me a riddle to solve.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Fun Fact Video", "description": "Video yourself telling a fun fact while jumping.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Favorite Word", "description": "Write your favorite word in fancy letters.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Number Hunt", "description": "Find the number 7 somewhere and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Love You Yell", "description": "Go outside (or pillow scream) ''I Love You''.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Meme Recreation", "description": "Recreate a famous meme and send the photo.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Lip Sync", "description": "Send a video lip-syncing to your favorite song.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Mirror Note", "description": "Write a love note on a mirror/window and send a pic.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Dance Party", "description": "Have a 1-minute solo dance party and share the video.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Sentimental Item", "description": "Share a photo of an object you cherish and tell its story.", "durationMinutes": 10, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Pillow Fort", "description": "Build a mini pillow fort (or a big one!) and send a pic.", "durationMinutes": 15, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Impression", "description": "Send a voice note of your best impression of me.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Virtual Date Invite", "description": "Design a digital invitation for our next date.", "durationMinutes": 10, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Power Pose", "description": "Strike a superhero pose and hold it for 1 minute. Send pic.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Fridge Poetry", "description": "Create a poem using items in your fridge/pantry.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Bad Hair Day", "description": "Style your hair in the craziest way possible.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Childhood Photo", "description": "Find a photo of you as a child and share it.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Handwritten Letter", "description": "Write a short letter by hand and send a photo of it.", "durationMinutes": 10, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Walk & Talk", "description": "Go for a walk while on a call with me.", "durationMinutes": 15, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Outfit Swap", "description": "Put on one of my clothing items (if possible) or style an outfit I''d wear.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Dramatic Reading", "description": "Read a grocery list or text message dramatically.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Bucket List Add", "description": "Add one new item to your personal bucket list and share it.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Wallpaper Change", "description": "Change your phone wallpaper to a photo of us and screenshot it.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Stretch Challenge", "description": "Try to touch your toes without bending knees. Send proof!", "durationMinutes": 2, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Songwriting", "description": "Write 4 lines of a song about our relationship.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Filter Fun", "description": "Use a silly face filter and record a message.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Appreciation Voice Note", "description": "Send a voice note listing 3 things you appreciate about your life.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Digital Scrapbook", "description": "Create a collage of our favorite memories.", "durationMinutes": 15, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Quick Workout", "description": "Do 10 jumping jacks, 10 squats, 10 pushups. Report back.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Cooking Challenge", "description": "Make a snack that looks like an animal.", "durationMinutes": 15, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Slow Mo", "description": "Record a mundane activity in slow motion.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Letter to Future", "description": "Write a short note to our future selves.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Playlist Add", "description": "Add a song to our shared playlist (or create one).", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Nature Walk", "description": "Find a flower or cool leaf outside and send a pic.", "durationMinutes": 10, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Portrait Mode", "description": "Take an artistic portrait of your pet or a plant.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Accent Challenge", "description": "Speak in a fake accent for 1 minute on a voice note.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Kindness Act", "description": "Do one small act of kindness today and share what it was.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Date Plan", "description": "Plan a hypothetical date night with unlimited budget.", "durationMinutes": 10, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Stair Climb", "description": "Climb a flight of stairs (or step up/down) for 1 min.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Book Title", "description": "Rename a book you own to something funny.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Dad Joke", "description": "Record yourself telling a dad joke. Try not to laugh.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Self-Care", "description": "Do one self-care activity and send a photo.", "durationMinutes": 15, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Love Coupon", "description": "Draw a coupon for a free massage/chore and send it.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Yoga Flow", "description": "Do a sun salutation sequence and share a timelapse.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Napkin Origami", "description": "Fold a napkin into a cool shape.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Magic Trick", "description": "Learn a simple magic trick and perform it on video.", "durationMinutes": 10, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Resolution Check", "description": "Share one step you took towards a goal today.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Virtual Background", "description": "Set your zoom/phone background to a photo of us.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Plank Variation", "description": "Try a side plank for 30 seconds each side.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Fruit Carving", "description": "Carve a design into an apple or orange.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Reverse Video", "description": "Record a video of you doing something, then play it in reverse (if app allows) or act in reverse.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Unplug", "description": "Spend 1 hour without your phone. Tell me how it felt.", "durationMinutes": 60, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Poem Reading", "description": "Read a romantic poem on a voice note.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Wall Pushups", "description": "Do 20 wall pushups.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Shadow Hand", "description": "Make a shadow puppet that looks like a dog.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "No Thumbs", "description": "Try to type a message without using your thumbs.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Learning", "description": "Watch a 5-min educational video and summarize it.", "durationMinutes": 15, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Appreciation List", "description": "List 5 things you appreciate about our relationship.", "durationMinutes": 10, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Balance Challenge", "description": "Stand on one leg while brushing your teeth (or pretending to).", "durationMinutes": 2, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Coffee Art", "description": "Try to make latte art (or just a design with spoon).", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Whisper Challenge", "description": "Record a whispered message. Can I guess what you said?", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Memory Lane", "description": "Scroll to the very first texts we sent. Share a screenshot.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Love Map", "description": "Draw a map of places significant to our relationship.", "durationMinutes": 15, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Chair Squats", "description": "Do 15 squats tapping your butt to a chair.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Cloud Watching", "description": "Lie down outside and find a shape in the clouds.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Gargle Song", "description": "Gargle water while humming a song. Can I guess it?", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Dream Job", "description": "Describe your childhood dream job vs. now.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Virtual Tour", "description": "Take me on a virtual tour of your room/house.", "durationMinutes": 10, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "High Jumps", "description": "Jump as high as you can 5 times.", "durationMinutes": 2, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Pebble Art", "description": "Arrange pebbles/stones into a shape.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Robot Dance", "description": "Do your best robot dance.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Role Model", "description": "Share a photo of your role model and why.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Holding Hands", "description": "Send a video of you reaching out to hold my hand.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Calf Stretch", "description": "Stretch your calves on a step.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Leaf Rubbing", "description": "Do a leaf rubbing with pencil and paper.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Funny Walk 2", "description": "Walk like a penguin and send a video.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Advice to Self", "description": "Record a video giving advice to your younger self.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Eye Gaze", "description": "Record a video looking deeply into the camera.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Arm Circles", "description": "Do arm circles for 1 minute.", "durationMinutes": 2, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Paper Airplane", "description": "Design a unique paper airplane.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Mime", "description": "Act out an activity without words or props.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Proud Achievement", "description": "Share a small achievement from this week.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Virtual Kiss 2", "description": "Send a video blowing a kiss in slow motion.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Side Lunges", "description": "Do 10 side lunges each leg.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Blind Contour", "description": "Draw your hand without looking at the paper.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Opera Singer", "description": "Sing a sentence of your day in opera style.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Gratitude Nature", "description": "Find something in nature you appreciate.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Hand Heart", "description": "Make a heart with your hands and frame something you love.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Shadow Boxing", "description": "Shadow box for 1 minute.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Recycle Art", "description": "Make a sculpture out of recyclable items.", "durationMinutes": 15, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Animal Impression", "description": "Act like your favorite animal.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Book Passage", "description": "Read a meaningful passage from a book.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Love Letter", "description": "Write a 3-sentence love letter.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Desk Yoga", "description": "Do a seated spinal twist.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Watercolour", "description": "Paint a quick watercolour (or use coffee!).", "durationMinutes": 15, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Kazoo", "description": "Pretend to play a kazoo with your voice.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Mentor", "description": "Who has been a mentor to you?", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Slow Dance", "description": "Slow dance with a pillow (pretending it''s me).", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Doorway Stretch", "description": "Stretch your chest in a doorway.", "durationMinutes": 2, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Collage", "description": "Make a digital collage of things that make you happy.", "durationMinutes": 10, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "News Anchor", "description": "Report on your breakfast like a breaking news anchor.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Values Quote", "description": "Share a quote that represents your values.", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Sunset Watch", "description": "Watch the sunset (or sunrise) and think of me.", "durationMinutes": 15, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Glute Bridges", "description": "Do 15 glute bridges.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Flower Press", "description": "Find a flower and press it in a book.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Air Guitar", "description": "Play an epic air guitar solo.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Forgiveness Note", "description": "Write a note of forgiveness (to anyone) and burn/shred it (send pic).", "durationMinutes": 10, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Candlelight", "description": "Light a candle and send a video of the flame.", "durationMinutes": 5, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Quad Stretch", "description": "Stretch your quads while standing.", "durationMinutes": 2, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Pattern Hunt", "description": "Find a natural pattern (e.g., wood grain) and snap it.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Beatbox", "description": "Try to beatbox a rhythm.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Inspiration", "description": "Share a photo of something that inspired you today.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Star Gaze", "description": "Look at the stars and find a constellation.", "durationMinutes": 10, "isCompetition": false}'),
('active', 'challenge', '{"frequency": "daily", "title": "Bird Dog", "description": "Do the bird-dog exercise for 1 minute.", "durationMinutes": 5, "isCompetition": false}'),
('creative', 'challenge', '{"frequency": "daily", "title": "Shadow Profile", "description": "Trace your shadow profile on the ground.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Laugh Therapy", "description": "Force yourself to laugh out loud for 30 seconds.", "durationMinutes": 5, "isCompetition": false}'),
('deep', 'challenge', '{"frequency": "daily", "title": "Silence", "description": "Sit in silence for 5 mins and text me the first thought you had.", "durationMinutes": 5, "isCompetition": false}'),
('romantic', 'challenge', '{"frequency": "daily", "title": "Silly Dance", "description": "Do a silly dance and send a video.", "durationMinutes": 5, "isCompetition": false}'),
('fun', 'challenge', '{"frequency": "daily", "title": "Truth or Dare", "description": "Play a quick round of Truth or Dare over text.", "durationMinutes": 5, "isCompetition": false}'),

-- SPICY (20)
('spicy', 'challenge', '{"title": "Sensual Whisper", "description": "Send a voice note whispering something you want to do to your partner next time you see them.", "frequency": "daily", "durationMinutes": 2, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Mystery Photo", "description": "Send a non-nude but teasing photo (e.g., collarbone, silhouette) with a playful caption.", "frequency": "daily", "durationMinutes": 5, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Fantasy Text", "description": "Text your partner a short scenario of a fantasy you have involving them.", "frequency": "daily", "durationMinutes": 5, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Outfit Request", "description": "Tell your partner exactly what you’d love to see them wearing right now.", "frequency": "daily", "durationMinutes": 2, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Memory Lane", "description": "Remind your partner of the hottest moment you’ve shared together recently.", "frequency": "daily", "durationMinutes": 5, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Virtual Touch", "description": "Describe in detail how you would touch them if you were there right now.", "frequency": "daily", "durationMinutes": 5, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Morning Tease", "description": "Send a ''Good Morning'' text that hints at what you dreamt about them.", "frequency": "daily", "durationMinutes": 2, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Soundtrack of Desire", "description": "Send them a song that makes you think of them in a sensual way.", "frequency": "daily", "durationMinutes": 3, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "One Word Hint", "description": "Send defined one word that sums up your mood tonight. Let them guess the context.", "frequency": "daily", "durationMinutes": 1, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Daring Question", "description": "Ask them one question about their turn-ons that you''ve been too shy to ask.", "frequency": "daily", "durationMinutes": 3, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Screen Kiss", "description": "Send a short video blowing a kiss, but make it slow and deliberate.", "frequency": "daily", "durationMinutes": 2, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Rate the Craving", "description": "On a scale of 1-10, tell them how much you want them right now and why.", "frequency": "daily", "durationMinutes": 2, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Virtual Undressing", "description": "Describe taking off one item of their clothing piece by piece.", "frequency": "daily", "durationMinutes": 5, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Code Word", "description": "Create a secret code word for ''I want you'' and use it in a normal conversation today.", "frequency": "daily", "durationMinutes": 2, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Sensory Focus", "description": "Describe a smell or taste that reminds you of their skin.", "frequency": "daily", "durationMinutes": 3, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Command Game", "description": "Give your partner one simple, playful command to follow today (e.g., ''wear that perfume'').", "frequency": "daily", "durationMinutes": 2, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Shower Thoughts", "description": "Tell them if they crossed your mind in the shower today.", "frequency": "daily", "durationMinutes": 1, "isCompetition": false, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Gif War: Spicy Edition", "description": "Send a GIF that represents your current mood. Winner is the one who blushes first.", "frequency": "daily", "durationMinutes": 3, "isCompetition": true, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Blindfold Guess", "description": "Describe an object you are holding sensually. They have to guess what it is.", "frequency": "daily", "durationMinutes": 5, "isCompetition": true, "isSpicy": true}'),
('spicy', 'challenge', '{"title": "Compliment Attack", "description": "List 3 physical features you can''t wait to touch.", "frequency": "daily", "durationMinutes": 3, "isCompetition": false, "isSpicy": true}');

